# Generated by Django 4.2 on 2026-03-15 03:41

from django.db import migrations, models
import django.db.models.deletion
import pilgub.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_partai_logo_partai'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaslonGubernur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut_paslon', models.IntegerField(unique=True, verbose_name='Nomor Urut')),
                ('nama_cagub', models.CharField(max_length=100, verbose_name='Nama Cagub')),
                ('nama_cawagub', models.CharField(max_length=100, verbose_name='Nama Cawagub')),
                ('foto_paslon', models.ImageField(blank=True, null=True, upload_to=pilgub.models.path_dan_nama_unik_gubernur, verbose_name='Foto Paslon')),
                ('warna_hex', models.CharField(default='#808080', max_length=7, verbose_name='Warna')),
            ],
            options={
                'verbose_name_plural': 'Data Paslon Gubernur',
                'ordering': ['no_urut_paslon'],
            },
        ),
        migrations.CreateModel(
            name='RekapSuaraGubernur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_suara_tidak_sah', models.IntegerField(default=0, verbose_name='Total Suara Tidak Sah')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_pilgub', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Data Rekap Suara Gubernur',
            },
        ),
        migrations.CreateModel(
            name='KoalisiGubernur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.partai', verbose_name='Partai')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partai_pendukung', to='pilgub.paslongubernur', verbose_name='Paslon Gubernur')),
            ],
            options={
                'verbose_name_plural': 'Data Koalisi Gubernur',
            },
        ),
        migrations.CreateModel(
            name='DetailSuaraGubernur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0, verbose_name='Jumlah Suara')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pilgub', to='core.kecamatan', verbose_name='Kecamatan')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_wilayah', to='pilgub.paslongubernur', verbose_name='Paslon Gubernur')),
            ],
            options={
                'verbose_name_plural': 'Data Detail Suara Gubernur',
                'unique_together': {('kecamatan', 'paslon')},
            },
        ),
    ]
