# Generated by Django 4.2 on 2026-03-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_partai_logo_partai'),
        ('pilgub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapKokabPilgub',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Kabupaten',
                'verbose_name_plural': 'Rekap Suara Kokab',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.kabupatenkota',),
        ),
        migrations.AlterModelOptions(
            name='paslongubernur',
            options={'ordering': ['no_urut_paslon'], 'verbose_name_plural': 'Paslon Pilgub'},
        ),
        migrations.AlterModelOptions(
            name='rekapsuaragubernur',
            options={'verbose_name_plural': 'Rekap Suara Kecamatan'},
        ),
    ]
