# Generated by Django 4.2 on 2026-03-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_kabupatenkota_kode_kokab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paslon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut_paslon', models.IntegerField(unique=True, verbose_name='Nomor Urut')),
                ('nama_capres', models.CharField(max_length=100, verbose_name='Nama Capres')),
                ('nama_cawapres', models.CharField(max_length=100, verbose_name='Nama Cawapres')),
                ('foto_paslon', models.ImageField(blank=True, null=True, upload_to='paslon/', verbose_name='Foto Paslon')),
                ('warna_hex', models.CharField(default='#808080', max_length=7, verbose_name='Warna')),
            ],
            options={
                'verbose_name_plural': 'Data Paslon',
                'ordering': ['no_urut_paslon'],
            },
        ),
        migrations.CreateModel(
            name='RekapSuara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_suara_tidak_sah', models.IntegerField(default=0, verbose_name='Total Suara Tidak Sah')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_pilpres', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Data Rekap Suara',
            },
        ),
        migrations.CreateModel(
            name='Koalisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.partai', verbose_name='Partai')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partai_pendukung', to='pilpres.paslon', verbose_name='Paslon')),
            ],
            options={
                'verbose_name_plural': 'Data Koalisi',
            },
        ),
        migrations.CreateModel(
            name='DetailSuara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0, verbose_name='Jumlah Suara')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pilpres', to='core.kecamatan', verbose_name='Kecamatan')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_wilayah', to='pilpres.paslon', verbose_name='Paslon')),
            ],
            options={
                'verbose_name_plural': 'Data Detail Suara',
                'unique_together': {('kecamatan', 'paslon')},
            },
        ),
    ]
