# Generated by Django 4.2 on 2026-03-11 07:55

from django.db import migrations, models
import pilpres.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilpres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslon',
            name='foto_paslon',
            field=models.ImageField(blank=True, null=True, upload_to=pilpres.models.path_dan_nama_unik, verbose_name='Foto Paslon'),
        ),
    ]
