# Generated by Django 4.2 on 2026-03-11 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kokab', models.CharField(max_length=10, verbose_name='Kode Kab/Kota')),
                ('nama_kokab', models.CharField(max_length=100, verbose_name='Nama Kab/Kota')),
            ],
            options={
                'verbose_name_plural': 'Data Kabupaten Kota',
                'ordering': ['nama_kokab'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kecamatan', models.CharField(max_length=10, verbose_name='Kode Kecamatan')),
                ('nama_kecamatan', models.CharField(max_length=100, verbose_name='Nama Kecamatan')),
                ('kab_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatans', to='core.kabupatenkota', verbose_name='Kabupaten')),
            ],
            options={
                'verbose_name_plural': 'Data Kecamatan',
                'ordering': ['kab_kota', 'nama_kecamatan'],
            },
        ),
        migrations.CreateModel(
            name='Partai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_partai', models.CharField(max_length=100, verbose_name='Nama Partai')),
                ('no_urut_partai', models.IntegerField(unique=True, verbose_name='Nomor Urut')),
                ('logo_partai', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('warna_partai', models.CharField(default='#808080', max_length=7, verbose_name='Warna')),
            ],
            options={
                'verbose_name_plural': 'Data Partai',
                'ordering': ['no_urut_partai'],
            },
        ),
        migrations.CreateModel(
            name='TpsDptPilkada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekap_tps_pilkada', models.IntegerField(default=0, verbose_name='TPS Pilkada')),
                ('rekap_dpt_pilkada', models.IntegerField(default=0, verbose_name='DPT Pilkada')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tps_pilkada', to='core.kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Data TPS & DPT Pilkada',
            },
        ),
        migrations.CreateModel(
            name='TpsDptPemilu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekap_tps_pemilu', models.IntegerField(default=0, verbose_name='TPS Pemilu')),
                ('rekap_dpt_pemilu', models.IntegerField(default=0, verbose_name='DPT Pemilu')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tps_pemilu', to='core.kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Data TPS & DPT Pemilu',
            },
        ),
        migrations.CreateModel(
            name='HasilClustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cluster', models.IntegerField(default=0, verbose_name='Cluster')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clustering', to='core.kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Data Hasil Clustering',
            },
        ),
    ]
