# Generated by Django 4.2 on 2026-03-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabupatenkota',
            name='kode_kokab',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode Kab/Kota'),
        ),
        migrations.AlterField(
            model_name='kabupatenkota',
            name='nama_kokab',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Kab/Kota'),
        ),
        migrations.AlterField(
            model_name='kecamatan',
            name='kode_kecamatan',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode Kecamatan'),
        ),
        migrations.AlterUniqueTogether(
            name='kecamatan',
            unique_together={('kab_kota', 'nama_kecamatan')},
        ),
    ]
