# Generated by Django 4.2 on 2026-03-11 07:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_kabupatenkota_kode_kokab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partai',
            name='logo_partai',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.path_logo_unik),
        ),
    ]
