"""
Django settings for webgis_clustering project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b@ie7h8ua!0s6xkn%l8fz*p#7hb^ev^rs67hj#za15z3!c4op('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Harus di atas admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Library Tambahan (Admin & Export)
    'import_export',

    'django.contrib.humanize',
    # Local Apps
    'core',
    'pilpres',
    'pilgub',
    'pilwalbup',
    'pileg_ri',
    'pileg_prov',
    'pileg_kokab',
    'geojson',
]

# Konfigurasi Import/Export
IMPORT_EXPORT_USE_NATIVE_STR_ENCODING = True
# Lewati pencatatan log admin agar proses import Excel lebih cepat
IMPORT_EXPORT_SKIP_ADMIN_LOG = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webgis_clustering.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webgis_clustering.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'webgis_db',
        'USER': 'root',
        'PASSWORD': '',  # Kosongkan jika tidak ada password
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploaded Files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================================
# KONFIGURASI JAZZMIN ADMIN (TEMA & MENU DROPDOWN)
# ==========================================================
JAZZMIN_SETTINGS = {
    "site_title": "WebGIS Admin",
    "site_header": "WebGIS Clustering",
    "site_brand": "Admin Panel",
    "welcome_sign": "Selamat Datang di WebGIS Admin",
    
    "topmenu_links": [
        {"name": "Dashboard UI", "url": "/dashboard", "permissions": ["auth.view_user"]},
        {"app": "pilpres"},
        {"app": "pilgub"},
        {"app": "pilwalbup"},
        {"app": "pileg_ri"},
        {"app": "pileg_prov"},
        {"app": "pileg_kokab"},
        {"app": "geojson"},
    ],
    
    "show_sidebar": True,
    "navigation_expanded": False,
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core": "fas fa-globe",
        "pilpres": "fas fa-vote-yea",
        "pileg_ri": "fas fa-users",
        "pileg_prov": "fas fa-users",
        "pilgub": "fas fa-landmark",
        "pilwalbup": "fas fa-city",
        "pileg_kokab": "fas fa-users",
        "geojson": "fas fa-layer-group",
    },
}
