# Generated by Django 4.2 on 2026-03-15 09:42

from django.db import migrations, models
import django.db.models.deletion
import pilwalbup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_partai_logo_partai'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapKokabPilwalbup',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Kabupaten',
                'verbose_name_plural': 'Rekap Suara Kokab (Pilwalbup)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.kabupatenkota',),
        ),
        migrations.CreateModel(
            name='RekapSuaraWalbup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_suara_tidak_sah', models.IntegerField(default=0, verbose_name='Total Suara Tidak Sah')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_pilwalbup', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Rekap Suara Kecamatan (Pilwalbup)',
            },
        ),
        migrations.CreateModel(
            name='PaslonWalbup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut_paslon', models.IntegerField(verbose_name='Nomor Urut')),
                ('nama_calon', models.CharField(max_length=100, verbose_name='Nama Bupati/Walikota')),
                ('nama_wakil', models.CharField(max_length=100, verbose_name='Nama Wakil')),
                ('foto_paslon', models.ImageField(blank=True, null=True, upload_to=pilwalbup.models.path_dan_nama_unik_walbup, verbose_name='Foto Paslon')),
                ('warna_hex', models.CharField(default='#808080', max_length=7, verbose_name='Warna')),
                ('kab_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paslon_walbup', to='core.kabupatenkota', verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name_plural': 'Paslon Pilwalbup',
                'ordering': ['kab_kota', 'no_urut_paslon'],
                'unique_together': {('kab_kota', 'no_urut_paslon')},
            },
        ),
        migrations.CreateModel(
            name='KoalisiWalbup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kab_kota', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.kabupatenkota')),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partai', verbose_name='Partai')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partai_pendukung', to='pilwalbup.paslonwalbup', verbose_name='Paslon')),
            ],
            options={
                'verbose_name_plural': 'Data Koalisi Pilwalbup',
                'unique_together': {('kab_kota', 'partai')},
            },
        ),
        migrations.CreateModel(
            name='DetailSuaraWalbup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0, verbose_name='Jumlah Suara')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pilwalbup', to='core.kecamatan', verbose_name='Kecamatan')),
                ('paslon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_wilayah', to='pilwalbup.paslonwalbup', verbose_name='Paslon')),
            ],
            options={
                'verbose_name_plural': 'Data Detail Suara Pilwalbup',
                'unique_together': {('kecamatan', 'paslon')},
            },
        ),
    ]
