# Generated by Django 4.2 on 2026-03-18 11:39

from django.db import migrations, models
import django.db.models.deletion
import pileg_ri.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_partai_logo_partai'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapSuaraPilegRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_suara_tidak_sah', models.IntegerField(default=0, verbose_name='Total Suara Tidak Sah')),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_pileg_ri', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Rekap Suara Kecamatan (Pileg RI)',
            },
        ),
        migrations.CreateModel(
            name='DapilRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dapil', models.CharField(max_length=100, verbose_name='Nama Dapil')),
                ('jumlah_kursi', models.IntegerField(default=0, verbose_name='Jumlah Kursi')),
                ('wilayah_kokab', models.ManyToManyField(related_name='dapil_ri', to='core.kabupatenkota', verbose_name='Cakupan Wilayah (Kab/Kota)')),
            ],
            options={
                'verbose_name_plural': 'Dapil RI',
                'ordering': ['nama_dapil'],
            },
        ),
        migrations.CreateModel(
            name='CalegRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_caleg', models.CharField(max_length=100, verbose_name='Nama Caleg')),
                ('no_urut', models.IntegerField(default=1, verbose_name='Nomor Urut')),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin')),
                ('foto_caleg', models.ImageField(blank=True, null=True, upload_to=pileg_ri.models.path_dan_nama_unik_caleg_ri, verbose_name='Foto Caleg (Opsional)')),
                ('dapil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caleg', to='pileg_ri.dapilri', verbose_name='Dapil')),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caleg', to='core.partai', verbose_name='Partai')),
            ],
            options={
                'verbose_name_plural': 'Caleg RI',
                'ordering': ['dapil', 'partai', 'no_urut'],
                'unique_together': {('dapil', 'partai', 'no_urut')},
            },
        ),
        migrations.CreateModel(
            name='DetailSuaraPilegRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0, verbose_name='Jumlah Suara')),
                ('caleg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suara_pileg_ri', to='pileg_ri.calegri', verbose_name='Caleg')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pileg_ri', to='core.kecamatan', verbose_name='Kecamatan')),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_pileg_ri', to='core.partai', verbose_name='Partai')),
            ],
            options={
                'verbose_name_plural': 'Data Detail Suara (Pileg RI)',
                'unique_together': {('kecamatan', 'partai', 'caleg')},
            },
        ),
    ]
