# Generated by Django 4.2 on 2026-03-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_partai_logo_partai'),
        ('pileg_ri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapSuaraPilegRIDapil',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Suara Dapil (Pileg RI)',
                'verbose_name_plural': 'Rekap Suara Dapil (Pileg RI)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pileg_ri.dapilri',),
        ),
        migrations.CreateModel(
            name='RekapSuaraPilegRIKab',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Suara Kokab (Pileg RI)',
                'verbose_name_plural': 'Rekap Suara Kokab (Pileg RI)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.kabupatenkota',),
        ),
    ]
